### PR TITLE
Fix various problems in Class Scheduling example for issue #76

### PR DESCRIPTION
**Pull request by kaiavintr**
The following two changes were required to allow spawning tasks using Tokio:
- Call `rand::thread_rng()` each time the random number generator is needed, instead of storing the rng or passing it as a parameter. The thread-local random number generator cannot be passed between threads, so this was preventing the futures returned by some of the async functions from being Send.
- Use `transact_boxed` instead of `transact_boxed_local`, so that the returned future is Send

After making the above changes, `tokio::task::spawn` can be used instead of thread::spawn (with no need to call `block_on`).
The return value of `tokio::task::spawn` is a different kind of `JoinHandle`, and the code needs to `.await` it instead of calling `join()`.

Remove some comments that are not meaningful to the reader of the example code.

Add a note explaining how the database will be modified by running the code (especially since it does not use a directory).

Make the parameters of the simulation (number of students and number of operations to attempt per student) const values for clarity.

Instead of using all 1,620 class names, and initializing the seat counts to 100, use const values for number of classes and initial number of seats, choosing a random selection of class names from the list of possible combinations.

Use subspaces consistently throughout the code.
When getting the key range for querying the attends keys for the student, use the .subspace method to get a Subspace struct for the prefix. Add a comment explaining this because it seems confusing/unintuitive (but I don't think the API provides a better way of doing it).

Pass false for the snapshot parameter to the `get` method, and add comments explaining why this is important (since this could be a major gotcha for someone new to the API).

Make `ditch_trx` and `signup_trx` both return bool values indicating whether the operation was performed. If the user was not in the class, or was already in the class, return false. Obviously it could return an `Err` here to cancel the transaction, but returning success values other than `()` adds variety to the example code.

Make `switch_classes()` handle the cases where the student was not in the old class, or was already in the new class, canceling the transaction in each case. Define two new error codes for the two cases.

In `perform_op`, check the return values of `ditch` and `signup`, and update `my_classes` only if the operation succeeds. A similar change is not required for the switch case, because that will return an error result.

Log the operations that were successfully performed, to make the simulation more interesting. (The code already has commented-out `println`s inside the transactions, but that logs operations even if they failed, or logs them multiple times if the transaction is repeated, which produces very cluttered and confusing output.)

Add a comment explaining why `get_available_classes` is called when it is, since that is one of the more confusing parts of the example.

Prevent panics when trying to choose values from `my_classes` or `available_classes` and the vectors are empty.

Use `get_ranges_keyvalues` and `get_ranges` instead of `get_range`, since `get_range` is not recommended for use by application code and has a confusing parameter (see #71 / #72).
In `get_available_classes` and `signup_trx`, use `get_ranges_keyvalues` the easy way, using `.try_collect()` to first get all results as a vector.
In `run_sim`, provide a commented-out example of iterating through the `Stream` returned by `get_ranges_keyvalues`, but use `get_ranges` here instead.

### CODE REVIEW

File: foundationdb/examples/class-scheduling.rs [hunk 1]
```diff
@@ -201,13 +248,13 @@ async fn signup_trx(trx: &Transaction, student: &str, class: &str) -> Result<()>
...
     trx.set(&attends_key, &pack(&""));
 
-    Ok(())
+    Ok(true)
 }
 
-async fn signup(db: &Database, student: String, class: String) -> Result<()> {
-    db.transact_boxed_local(
+async fn signup(db: &Database, student: String, class: String) -> Result<bool> {
+    db.transact_boxed(
```
Comment (PierreZ) [inline foundationdb/examples/class-scheduling.rs:255]: Could you remove the transact_boxed and use `db.run`, to make it more like the [java bindings](https://apple.github.io/foundationdb/class-scheduling-java.html#signing-up-for-a-class)?

File: foundationdb/examples/class-scheduling.rs [hunk 2]
```diff
@@ -150,32 +180,40 @@ async fn ditch_trx(trx: &Transaction, student: &str, class: &str) {
...
     trx.set(&class_key, &pack(&available_seats));
     trx.clear(&attends_key);
+    
+    Ok(true)
 }
 
-async fn ditch(db: &Database, student: String, class: String) -> Result<()> {
-    db.transact_boxed_local(
+async fn ditch(db: &Database, student: String, class: String) -> Result<bool> {
+    db.transact_boxed(
```
Comment (PierreZ) [inline foundationdb/examples/class-scheduling.rs:188]: Could you remove the transact_boxed and use `db.run`, to make it more like the [java bindings](https://apple.github.io/foundationdb/class-scheduling-java.html#appendix-classscheduling-java)?

**Review by PierreZ — CHANGES_REQUESTED** [review]
Nice work @kaiavintr :clap: 
Clippy seems to be not passing, and I left a comment. Otherwise, LGTM :+1:

**Comment by kaiavintr** [comment]
I have now fixed the Clippy issues.

I started trying to use the `run` method, but immediately ran into difficulties.
I was hoping it would only require minor changes to the `transact_boxed` calls, but it looks like some other code will need to be modified. Custom errors need to be handled differently, since they are boxed and wrapped in FdbBindingError::CustomError.

The class-scheduling.rs file is the example code for people using 0.7.0 (the documentation links to the examples folder in github), so there still needs to be a version of it that will compile with 0.7.0. 
I will make a copy called "class-scheduling-0_7_0.rs" (dots are not allowed in the name) with the changes I have committed so far, and then try changing the original file to use `run`. Hopefully that name will be obvious enough for people to find it.

**Comment by kaiavintr** [comment]
Sorry, I didn't realize that some of the errors are differences with the output of "cargo fmt". I will fix those formatting issues now.

**Comment by kaiavintr** [comment]
I noticed there is an infinite recursion in Debug::fmt and Display::fmt for FdbBindingError, e.g. these will overflow the stack:
    println!("{}", FdbBindingError::ReferenceToTransactionKept);
    println!("{:?}", FdbBindingError::ReferenceToTransactionKept);

**Comment by kaiavintr** [comment]
I realized that it is probably still too confusing if someone tries to use the example with 0.7.0 and does not notice the new class-scheduling-0_7_0.rs file.

I will work on adding descriptions of the examples to the README.md file, and also add a comment at the top of class-scheduling.rs (which could be removed after the next release).

**Comment by PierreZ** [comment]
Sorry for the long delay, nice work :clap: 

I agree with you, keeping two `class-scheduling.rs` is a bit too confusing. I think we can keep only one class-scheduling, and having comments about transact_boxed methods. 

I have some minors comments, but I think we can merge your work once we have one class-scheduling, if you are okay with this.

**Comment by kaiavintr** [comment]
Unfortunately it looks like the extra file is necessary, because this code still serves as part of the documentation for 0.7.0. (There are links from the 0.7.0 documentation to his folder.) If anyone tries to use the new example code with the 0.7.0 crate and sees compilation errors, they will probably just give up (because changing the code so it works with 0.7.0 is not trivial).

I think it's clearer now, with the updates to README.md and the additional comments in the source, but let me know if you'd like me to change anything, or if there's a better solution to the compatibility problem.

If this needs more discussion, I can add details to #59.

**Comment by kaiavintr** [comment]
Ok, in that case I will remove class-scheduling-0_7_0.rs from the PR. Hopefully it will not be long before the 0.8.0 release.

**Review by PierreZ — APPROVED** [review]

**Comment by PierreZ** [comment]
Something is wrong on the Code coverage check, I will [try to bump the version](https://github.com/coverallsapp/github-action/issues/55#issuecomment-644828191).

**Comment by PierreZ** [comment]
@kaiavintr, can you rebase your work? I pushed a commit on main that should fix the CI

**Comment by kaiavintr** [comment]
Would you prefer a squash commit, or should I leave the 7 individual commits when rebasing?

**Comment by PierreZ** [comment]
> Would you prefer a squash commit, or should I leave the 7 individual commits when rebasing?

If you don't mind, a squash commit is prefered :smile:

**Comment by kaiavintr** [comment]
Ok, it's rebased and squashed to two commits now (I think keeping the .run() changes in a separate commit makes it more clear).

**Comment by PierreZ** [comment]
Something is wrong, there is no CI associated to this PR :thinking: 

the PR correcness has been triggered by me, but there should be others
image

**Comment by PierreZ** [comment]
@kaiavintr, could you trigger the CI by pushing/altering a commit? Something seems wrong

**Comment by kaiavintr** [comment]
Do you still need me to do this? I was trying to figure out how to change the pull request without actually changing anything. Does it need to be a meaningful change in a .rs file in order to trigger the CI?
